# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
### post_install_script Module
#
# This module runs a script after the installation is complete.
#

---

#
# The name of the script to be displayed to the user
name: "Run Post-Install Script"
#
# The path to the script
# When runInTarget is true the path should be relative to the installed system
# When runInTarget is false the path should be an absolute path on the host
scriptPath: "/data/scripts/post_install.sh"
#
# A boolean value which determines if the script should be run in the host or in the target
runInTarget: true
#
# When true the command line will include "--root=" followed by the path to the installed root
includeRoot: true
#
# When true the command line will include "--user=" followed by the username configured in calamares
includeUser: true
#
# When true the command line will include only the username configured in calamares
includeRawUser: false
#
# When true the command line will include "--online" if this is an online install
isOnline: true
#
# When true, each line of output from the script will be displayed in calamares
#
# Unless the script is long-running it is generally to leave this false
userOutput: true
